define({ root:
{
/* General resources */
search: "搜索",
filter: "过滤",
"new": "创建",
errorSavingFile: "文件保存错误: ${0} 详细信息: ${1}",
"palette":"组件库",

/* Menu items on file tabs */
"closeAllEditors":"关闭所有标签",

/* actions */
undo: "撤销",
redo: "重做",
copy: "复制",
paste: "粘贴",
cut: "剪切",
"delete": "删除",
surround: "环绕",
properties: "属性",
styles: "风格",
events: "事件",
preferences: "偏好",

addPane: "添加面板",
addColumn: "添加列",
addRow: "添加行",
removeColumn: "删除列",
removeRow: "删除行",
joinColumn: "和并列",
joinRow: "合并行",
splitColumn: "分割列",
splitRow: "分割行",
alignLeft: "左对齐",
alignRight: "右对齐",
alignTop: "上对齐",
alignBottom: "下对齐",
show: "显示",
hide: "隐藏",
addMenuItem: "添加菜单元素",
addSubMenu: "添加子菜单",
addMenuBarItem: "添加菜单条元素",
addPopupMenuBar: "添加弹出式菜单条元素",

/* dialogs */
ok: "确认",
cancel: "取消",

/* PropertyPane */
page: "页面",
title: "标题",
metaInfo: "元信息（Meta Info）",
httpEquiv: "HTTP Equiv",
style: "风格",
theme: "主题",
styleSheets: "样式表",
rules: "规则Rules",
url: "URL",
externalScripts: "外部脚本",
modules: "模块",
name: "名称",
value: "指",
add: "添加",
remove: "移除",

staticOptions: "Static Options",
axisOptions: "Axis Options",
series: "Series",
axis: "Axis",
option: "Option",
selected: "Selected",
staticItems: "Static Items",
dataStore: "Data Store",
query: "Query",
fields: "Fields",
field: "Field",
label: "Label",
width: "Width",
edit: "Edit",
key: "Key",
rootId: "Root ID",
rootLabel: "Root Label",
childrenAttrs: "Children Attributes",
items: "Items",
type: "Type",
widget: "Widget",

/* StylePane */
position: "Position",
size: "Size",
layout: "Layout",
visual: "Visual",
text: "Text",
border: "Border",
table: "Table",
list: "List",
aural: "Aural",
others: "Others",

/* EventPane */
onLoad: "Load",
onUnload: "Unload",
script: "Script",
methodCall: "Method Call",
serviceCall: "Service Call",
object: "Object",
method: "Method",
parameters: "Parameters",
result: "Result",
service: "Service",
type: "Type",
content: "Content",
source: "来源",
target: "Target",
property: "Property",

/* PreferencePane */
flowLayout: "流式布局",
snapToNearestWidget: "靠近最近的小工具",
showPossibleParents: "拖拽时，显示可放置的父元素",
warnOnCSSOverride: "CSS改写时警告",
absoluteWidgetsZindex: "在草图模式中使用z-index",
widgetPaletteLayout: "在控件库中，小工具显示为",
widgetPaletteShow_Icons: "图标",
widgetPaletteShow_List: "列表",
liveEdit: "实时编辑",
zazl: "启用 <a href='http://zazl.org' target='_blank'>Zazl Optimizer</a>",

/* WidgetSelectionPane*/
selectorPrefix: "选择器前缀",
component: "组件",

/* Palette*.js */
alternates: "替代元素",
alternateWidgets: "替代小工具:",
howToChooseAlternate: "若要使用替代小工具, 选中当前小工具, 然后点击上箭头.",
summary: "概述:",
description: "描述:",
showSuggestedWidgets: "推荐的小工具",
showAllWidgets: "所有小工具",
MoreIconTitleString: "点击这里查看相似的替代小工具",
HelpIconTitleString: "点击这里查看小工具的描述信息",

__dummy__: ""
}
});
